build:
  image: latest

conda:
  environment: docs/env.yml

python:
  version: 2.7
  pip_install: true
requirements_file: docs/docs_requirements_py2.txt

  
python:
    extra_requirements:
        - sphinx-argparse
        - mysql-connector-python-rf
