version: 2

build:
  image: latest

conda:
  environment: docs/env.yml
  
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      extra_requirements:
        - sphinx-argparse
        - mysql-connector-python-rf
