checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - '*/test/*'
        - '*.min.js'
build:
    environment:
        python: 3.7.4


build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
